# Generated by Django 2.2.2 on 2019-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_no',
            field=models.IntegerField(default=438530, primary_key=True, serialize=False),
        ),
    ]
